services:
  springbootapp:
    build: .
    image: springbootapp
    container_name: springbootapp
    ports:
      - "8180:8080"
    networks:
      - webnet

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/resources/static:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
