version: '3'
services:
  devapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: authorizationapp
    container_name: auth-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - webnet

  prodapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: authorizationapp
    container_name: auth-prod
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

